name = "Erick Merchant"

objective = """
I am currently looking for a full-time role as a front-end engineer or full-stack engineer. I would love if that role involved Rust, Deno, Typescript, CSS, Preact, Vue, Lit, or similar technologies. I take pride in building things for the web platform, programming, and solving difficult problems with computers.
"""

[[contacts]]
href = "mailto:erickmerchant@gmail.com"
text = "erickmerchant@gmail.com"

[[contacts]]
href = "https://erickmerchant.com"
text = "erickmerchant.com"

# [[history]]
# title = "Open-source creator"
# dates = ["May 2014", "present"]
# tags = ["Rust", "JavaScript", "CSS"]
# summary = """
# - Created [Handcraft](https://github.com/erickmerchant/handcraft), a front-end library for creating declarative UI with reactive state using a jQuery inspired API
# - Created [Cool Style Server](https://github.com/erickmerchant/coolstyleserver), a development server that does live-reloading for CSS for designing in the browser without the need of NPM
# """

# [[history]]
# title = "Freelance writer"
# dates = ["Sept 2024", "present"]
# tags = ["Writing", "JavaScript", "CSS"]
# summary = """
# So far I've written an article about JavaScript loops for [CSS-Tricks](https://css-tricks.com/all-about-javascript-loops/). I plan to write more. I love to blog on my [personal site](https://erickmerchant.com/), but for now I'm mostly focused on paid writing.
# """

[[history]]
title = "Engineering Consultant"
# organization = "Music studio"
dates = ["May 2025", "Present"]
# location = "Los Angeles, CA"
tags = ["Next.js", "React", "CSS", "Node.js", "Mongo"]
summary = """
- Worked to visualize particular scientific data using ArcGIS maps
- Used an established design system to maintain consistency with other sites in the same organization
- Designed a database schema to hold the data, aggregating it from different sources
- Worked with a CMS (Payload) for secondary site content like a blog and faq.
- Developed sign-in, forgot password, and change password forms
"""

[[history]]
title = "Freelance Engineer"
# organization = "Music studio"
dates = ["Mar 2024", "Dec 2024"]
# location = "Los Angeles, CA"
tags = ["Python", "React", "Next.js", "AI"]
summary = """
- Worked on an application with a Python (FastAPI) service, and a TypeScript service (Next.js)
- Created React components and worked with Redux and XState
- Implemented search features that utilized AI services
- Utilized SQLAlchemy to save application state per user and organization (managed by Clerk)
- Worked with Supabase and Retool for rapid development of simple dashboards
- Implemented a bespoke analytics system to gain insight into how the application was used
"""

[[history]]
title = "Senior Software Engineer"
dates = ["Oct 2021", "Mar 2024"]
organization = "WorkStep"
location = "San Francisco, CA"
tags = ["React", "Typescript", "GraphQL", "Python"]
summary = """
- Used Python and React to build out features for an employee listening platform targeted towards frontline workers
- Made charts, tables, and the forms where feedback was gathered
- Established conventions for more maintainable CSS
- Improved build times by adopting SWC and doing other improvements which directly saved the company money and developers' sanity
- Added front-end testing, and wrote many of the initial tests, which then allowed us to migrate to TypeScript
- Worked on adopting GraphQL in a successful effort to scale the application
- Did pair programming and one-on-one meetings with fellow engineers to facilitate problem solving (unblocking) and education
"""

[[history]]
title = "Senior Software Engineer"
dates = ["Aug 2019", "Oct 2021"]
organization = "Brightspot"
location = "Reston, VA"
tags = ["HTML", "CSS", "Web Components", "Java"]
summary = """
- Developed HTML, CSS, and JavaScript for client websites
- Worked with Java to tailor their proprietary CMS to the requirements of each project
- Learned a great deal about web components and have used them ever since
- Helped junior developers who mostly just knew Java with the the front-ends of their assigned sites
- Improving accessibility on several sites by fixing issues flagged in audits
"""

[[history]]
title = "Senior Developer"
dates = ["May 2012", "Jul 2019"]
organization = "Adpearance"
location = "Portland, OR"
tags = ["HTML", "CSS", "JavaScript", "Vue", "PHP", "Node.js", "Java"]
summary = """
- Started as one of three developers and helped grow the company into several engineering teams: two product, one maintenance, and one project focused
- Used my expert level skills with PHP to develop client sites (e-commerce focused)
- Wrote plugins and authored templates for use in our ExpressionEngine sites
- Drove the adoption of Composer for dependency management
- Created a role as a front-end JavaScript engineer before that was a widespread career path
- Created the admin for their proprietary Java (Spring Boot) CMS called Foursite using jQuery and Node.js and later Vue
- Worked with one other engineer to successful develop the CMS, allowing Adpearance to break into new markets, namely large equipment sites like John Deere dealerships for example
- Later for about 5 years, I was the unofficial lead of a team devoted solely to the development of the CMS as a product
- Drove the adoption of git, moving the company away from risky and frustrating ftp practices
- Wrote web-scrapers (using PHP and later Node.js) to migrate content from one system into another
- Authored many build tools in Node.js such as the tool that managed our Java projects. The IDE was too slow so I wrote something much faster
- Created Dashboards, and internal tools for direct marketing teams and others
- Mentored others in how to write good PHP, fast JavaScript, and manageable CSS
"""

[[history]]
title = "Developer"
dates = ["Jun 2006", "May 2012"]
organization = "NetBiz, Inc."
location = "Tualatin, OR"
tags = ["HTML", "CSS", "JavScript", "PHP"]
summary = """
- Developed software using the LAMP stack
- Wrote Flash applications
- Took PDFs from designers and created pixel for pixel perfect templates in HTML and CSS from them
- Introduced Ajax and used it to accomplish things on sites that had not yet ever been done at the company
- Introduced the company to jQuery and became an expert in its usage
- Worked on internal dashboards as well, and worked on their proprietary CMS
- Built the company's site which was obviously a big honor and responsibility
"""

[[education]]
title = "A.A.S., Web Design"
dates = ["January 2005", "May 2006"]
organization = "Tompkins-Cortland Community College"
location = "Dryden, NY"
summary = """
- Graduated with a 4.0 GPA
- Studied web technologies, programming, and design
- Gained a significant head start in my career, because I was typically the only one that had had courses on JavaScript, CSS, and PHP at most jobs for many years
"""

[[education]]
title = "B.A., Anthropology"
dates = ["September 1997", "May 2002"]
organization = "University at Albany"
location = "Albany, NY"
summary = """
- Majored in Anthropology with a focus in linguistics
- Studied English literature
- Studied Greek, Roman, and Egyptian history extensively
- Did my work study program assisting an anthropology professor with editing of his publications and cataloging of artifacts
"""
